steps:
  - if: build.branch == "main"
    if_changed: ".buildkite/Dockerfile.build"
    key: base_image
    label: ":docker: Create base image"

  - group: ":mag: QA"
    id: quality_checks
    depends_on: [base_image]
    steps:
      - key: lint
        label: ":golangci-lint: lint"
        command: golangci-lint run --verbose --timeout 3m

      - key: test
        label: ":go: test"
        artifact_paths:
          - cover-tree.svg
          - coverage.out
        env:
          DYNAMODB_TABLE: airunner_test
          DYNAMODB_ENDPOINT: http://localhost:4101
        commands:
          - docker compose -f .buildkite/docker-compose.yml up dynamodb --wait -d
          - go test -coverprofile coverage.out -coverpkg=./... ./...
          - go run github.com/nikolaydubina/go-cover-treemap -coverprofile coverage.out > cover-tree.svg
          - echo '<details><summary>Coverage tree map</summary><img src="artifact://cover-tree.svg" alt="Test coverage tree map" width="70%"></details>' | buildkite-agent annotate --style "info"
