package store

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/wolfeidau/airunner/internal/models"
)

// Sentinel errors for session store operations
var (
	ErrSessionNotFound = errors.New("session not found")
	ErrSessionExpired  = errors.New("session expired")
)

// SessionStore defines the interface for session storage operations.
// Sessions are server-side storage for authenticated user sessions.
// The cookie contains only an opaque session ID (UUIDv7).
type SessionStore interface {
	// Create creates a new session in the store.
	// The session ID should be a UUIDv7 generated by the caller.
	Create(ctx context.Context, session *models.Session) error

	// Get retrieves a session by ID.
	// Returns ErrSessionNotFound if the session doesn't exist.
	// Returns ErrSessionExpired if the session exists but has expired.
	Get(ctx context.Context, sessionID uuid.UUID) (*models.Session, error)

	// UpdateLastUsed updates the last_used_at timestamp for a session.
	// This should be called periodically to track session activity.
	// Returns ErrSessionNotFound if the session doesn't exist.
	UpdateLastUsed(ctx context.Context, sessionID uuid.UUID) error

	// Delete deletes a session by ID (logout).
	// Returns ErrSessionNotFound if the session doesn't exist.
	Delete(ctx context.Context, sessionID uuid.UUID) error

	// DeleteByPrincipal deletes all sessions for a principal (logout everywhere).
	// Returns the number of sessions deleted.
	DeleteByPrincipal(ctx context.Context, principalID uuid.UUID) (int, error)

	// DeleteExpired deletes all expired sessions (cleanup job).
	// Returns the number of sessions deleted.
	DeleteExpired(ctx context.Context) (int, error)
}
